version: "3.7"
services:
  fpm:
    image: php:fpm
    volumes:
      - ../app:/var/www
  nginx:
    image: nginx
    ports:
      - "8080:80"    
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ../app:/var/www